//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string cmd_track_name {
            get {
                return ResourceManager.GetString("cmd_track_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track end.
        /// </summary>
        internal static string cmd_trackend_name {
            get {
                return ResourceManager.GetString("cmd_trackend_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToString template for the filename, first argument is the current datetime.
        /// </summary>
        internal static string conf_filename_template_description {
            get {
                return ResourceManager.GetString("conf_filename_template_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename template.
        /// </summary>
        internal static string conf_filename_template_label {
            get {
                return ResourceManager.GetString("conf_filename_template_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename template is not set. Please set it in the settings..
        /// </summary>
        internal static string conf_missing_filename_template {
            get {
                return ResourceManager.GetString("conf_missing_filename_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage folder is not set. Please set it in the settings..
        /// </summary>
        internal static string conf_missing_folderpath {
            get {
                return ResourceManager.GetString("conf_missing_folderpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where the tracking files are stored.
        /// </summary>
        internal static string conf_storagefolder_description {
            get {
                return ResourceManager.GetString("conf_storagefolder_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage folder.
        /// </summary>
        internal static string conf_storagefolder_label {
            get {
                return ResourceManager.GetString("conf_storagefolder_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not task is being tracked.
        /// </summary>
        internal static string msg_tracking_notstarted {
            get {
                return ResourceManager.GetString("msg_tracking_notstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking has started.
        /// </summary>
        internal static string msg_tracking_started {
            get {
                return ResourceManager.GetString("msg_tracking_started", resourceCulture);
            }
        }
    }
}
